/**
 * Build-time generator for the high-resolution body-texture manifest.
 *
 * The renderer loads body textures by string path (e.g.
 * `./assets/textures/bodies/8k/earth_day.jpg`), so at runtime there is no way
 * to ask "does an 8k variant of this texture exist?" without an HTTP probe.
 * Rather than pay a 404 per missing variant, this plugin scans the `4k` and
 * `8k` texture folders on disk — at build time and at dev-server start — and
 * exposes the filenames it finds through a virtual module. The resolver in
 * `src/drawing/texture-quality.ts` consumes that manifest to choose the best
 * available asset synchronously.
 *
 * Because the manifest is generated from the filesystem, it can never go stale:
 * adding or renaming a `4k`/`8k` asset is picked up automatically, and in dev
 * the affected folders are watched so a change reloads the page.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';

import type { Plugin, ViteDevServer } from 'vite';

/** Virtual module id imported by the renderer. */
const VIRTUAL_ID = 'virtual:texture-quality-manifest';
/** Rollup convention: a leading NUL marks an id as virtual and unresolvable on disk. */
const RESOLVED_ID = '\0' + VIRTUAL_ID;

/** Texture quality tiers above the 2k floor, best first. Mirrors the resolver's tier order. */
const HIGH_RES_TIERS = ['8k', '4k'] as const;
type HighResTier = (typeof HIGH_RES_TIERS)[number];

/** Body-texture root, relative to the Vite `root` (which is `src`). */
const BODIES_TEXTURES_DIR = path.join('assets', 'textures', 'bodies');

/**
 * Recursively collect every file under `dir`, returned as paths relative to
 * `baseDir` using forward slashes (so the strings match what the browser sees
 * regardless of the host OS separator).
 */
function collectRelativeFiles(baseDir: string, dir: string): string[] {
    const results: string[] = [];
    let entries: fs.Dirent[];
    try {
        entries = fs.readdirSync(dir, { withFileTypes: true });
    } catch {
        return results;
    }

    for (const entry of entries) {
        const absolute = path.join(dir, entry.name);
        if (entry.isDirectory()) {
            results.push(...collectRelativeFiles(baseDir, absolute));
        } else if (entry.isFile()) {
            results.push(path.relative(baseDir, absolute).split(path.sep).join('/'));
        }
    }
    return results;
}

/** Sorted relative filenames inside one quality tier, or `[]` when it is absent. */
function scanTier(viteRoot: string, tier: HighResTier): string[] {
    const tierDir = path.resolve(viteRoot, BODIES_TEXTURES_DIR, tier);
    if (!fs.existsSync(tierDir)) return [];
    return collectRelativeFiles(tierDir, tierDir).sort();
}

/** Source of the virtual module: the two tiers as JSON string arrays. */
function buildManifestSource(viteRoot: string): string {
    const eight = scanTier(viteRoot, '8k');
    const four = scanTier(viteRoot, '4k');
    return [
        `// Generated by vite-plugin-texture-manifest.ts — do not edit.`,
        `export const eightKTextures = ${JSON.stringify(eight)};`,
        `export const fourKTextures = ${JSON.stringify(four)};`,
        '',
    ].join('\n');
}

/** True when a dev-server change touches a `4k`/`8k` body texture. */
function isHighResBodyTexture(viteRoot: string, changedPath: string): boolean {
    const tierRoots = HIGH_RES_TIERS.map((tier) =>
        path.resolve(viteRoot, BODIES_TEXTURES_DIR, tier) + path.sep
    );
    return tierRoots.some((root) => changedPath.startsWith(root));
}

/**
 * Vite plugin that exposes `virtual:texture-quality-manifest` and keeps it in
 * sync with the `4k`/`8k` texture folders while the dev server runs.
 */
export function textureManifestPlugin(): Plugin {
    // Populated from the resolved config, since `root` (src) is not known at
    // plugin construction time.
    let viteRoot = process.cwd();

    /** Rebuild the virtual module and reload the page (dev only). */
    const invalidateManifest = (server: ViteDevServer): void => {
        const module = server.moduleGraph.getModuleById(RESOLVED_ID);
        if (module) {
            server.moduleGraph.invalidateModule(module);
        }
        server.ws.send({ type: 'full-reload' });
    };

    return {
        name: 'texture-quality-manifest',

        configResolved(config): void {
            viteRoot = config.root;
        },

        resolveId(id): string | null {
            return id === VIRTUAL_ID ? RESOLVED_ID : null;
        },

        load(id): string | null {
            return id === RESOLVED_ID ? buildManifestSource(viteRoot) : null;
        },

        configureServer(server): void {
            const bodiesDir = path.resolve(viteRoot, BODIES_TEXTURES_DIR);
            server.watcher.add(bodiesDir);

            const onChange = (changedPath: string): void => {
                if (isHighResBodyTexture(viteRoot, changedPath)) {
                    invalidateManifest(server);
                }
            };

            server.watcher.on('add', onChange);
            server.watcher.on('unlink', onChange);
            server.watcher.on('addDir', onChange);
            server.watcher.on('unlinkDir', onChange);
        },
    };
}
